name: hotels_booking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  bot_toast: ^4.0.3
  connectivity_plus: ^2.3.7
  cupertino_icons: ^1.0.2
  drift: ^2.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lorem: ^2.0.0
  get: 4.6.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  path: 1.8.1
  path_provider: ^2.0.0
  responsive_framework: ^0.2.0
  sensors_plus: ^1.3.4+1
  sqlite3_flutter_libs: ^0.5.0
  syncfusion_flutter_datepicker: ^20.2.50

dev_dependencies:
  build_runner: ^2.2.0

  drift_dev: ^2.1.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
